# Generated by Django 3.2.12 on 2022-02-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_auto_20220214_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('id',)},
        ),
    ]
